### ISSUE TITLE
File path issues

### ISSUE THREAD

**Issue by vinays6** [rtealwitter/OpenStreets#1]
Running benchmark.py results in file path issues:
`fiona.errors.DriverError: data/links.json: No such file or directory`
data.py has several filepaths beginning with 'data/...' while they should be '../data/...', as it's in a subdirectory. 
Just letting you know :smile:

**Comment by rtealwitter** [comment]
Hi! Thanks for your interest in our project :)

I just pulled and ran benchmark.py. I wasn't able to recreate the error that you described. Have you loaded all the packages in requirements.txt? If you're still having problems, would you mind providing more details?
